export const ABOUT_TEXT_REQUEST = 'ABOUT_TEXT_REQUEST';
export const ABOUT_TEXT_SUCCESS = 'ABOUT_TEXT_SUCCESS';
export const ABOUT_TEXT_FAIL = 'ABOUT_TEXT_FAIL';

export const USEFUL_LINKS_REQUEST = 'USEFUL_LINKS_REQUEST';
export const USEFUL_LINKS_SUCCESS = 'USEFUL_LINKS_SUCCESS';
export const USEFUL_LINKS_FAIL = 'USEFUL_LINKS_FAIL';

export const WHAT_WE_DO_REQUEST = 'WHAT_WE_DO_REQUEST';
export const WHAT_WE_DO_SUCCESS = 'WHAT_WE_DO_SUCCESS';
export const WHAT_WE_DO_FAIL = 'WHAT_WE_DO_FAIL';

export const HOW_TO_USE_REQUEST = 'HOW_TO_USE_REQUEST';
export const HOW_TO_USE_SUCCESS = 'HOW_TO_USE_SUCCESS';
export const HOW_TO_USE_FAIL = 'HOW_TO_USE_FAIL';

export const PRESS_RELEASE_REQUEST = 'PRESS_RELEASE_REQUEST';
export const PRESS_RELEASE_SUCCESS = 'PRESS_RELEASE_SUCCESS';
export const PRESS_RELEASE_FAIL = 'PRESS_RELEASE_FAIL';

export const PHOTO_GALLERY_REQUEST = 'PHOTO_GALLERY_REQUEST';
export const PHOTO_GALLERY_SUCCESS = 'PHOTO_GALLERY_SUCCESS';
export const PHOTO_GALLERY_FAIL = 'PHOTO_GALLERY_FAIL';
